- hosts: server1ic
  tasks:
    - name: testname=simulation1
      shell: grubby --args testname=simulation1 --update-kernel ALL
  
    - name: Run setup-simulation-1.sh
      script: setup-simulation-1.sh

    - reboot:

- hosts: server3ic
  tasks:
    - name: Postgresql is up and running
      wait_for:
        host: server1ic
        port: 5432
  
    - name: Run Test
      shell: /usr/local/bin/run.sh
      become: true
      become_user: testadm
      register: scriptout1

    - name: Save result 1
      local_action: copy content={{ scriptout1.stdout }} dest=./output1.txt


- hosts: server1ic
  tasks:
    - name: testname=simulation2
      shell: grubby --args testname=simulation2 --update-kernel ALL
  
    - name: Run setup script 2
      script: setup-simulation-2.sh

    - reboot:

- hosts: server3ic
  tasks:
    - name: Postgresql is up and running
      wait_for:
        host: server1ic
        port: 5432

    - name: Run Test
      shell: /usr/local/bin/run.sh
      become: true
      become_user: testadm
      register: scriptout2

    - name: Save result 2
      local_action: copy content={{ scriptout2.stdout }} dest=./output2.txt

    - name: Count
      set_fact:
        len1: "{{ scriptout1.stdout | length }}"
        len2: "{{ scriptout2.stdout | length }}"

    - set_fact:
        result: PASS
      when: len1 == len2

    - set_fact:
        result: FAIL
      when: len1 != len2

    - name: Compare
      local_action: copy content="{{ len1 }} {{ len2 }}\n{{ result }}\n" dest=./result.txt


 
